### ISSUE TITLE
System?

### ISSUE THREAD

**Issue by Universal32** [askkostya/KKTATOL#1]
Привет. Я так понимаю этот питоновский скрипт рассчитан на работу под линуксом?
У нас атолы 11, 22, 30, 50, 52, 55. Везде Win 7\10. ККТ10. Хотелось бы считывать данные и мониторить забиксом, но пока вообще не понял как это сделать. Буду рад подсказке. :)

**Comment by askkostya** [comment]
Здравствуйте. Нет, скрипт писался и используется в среде Windows.
1. Можно взять целиком файлы из https://github.com/askkostya/ZabbixUpdater и поместить их в C:\zabbix
2. Установить zabbix агент и прописать в Windows Path до интерпретатора Python (C:\zabbix\files\Python)
3. Дальше все работы уже производите на стороне сервера zabbix, импортируете шаблоны, добавляете агенты которые планируете мониторить
