### ISSUE TITLE
Скрипт на перезапуск.

### ISSUE THREAD

**Issue by arzol72** [askkostya/KKTATOL#4]
Добрый день.
Возник вопрос по подключению скрипта на перезапуск ФРа.
Я так понимаю, что нужно создать новый скрипт с выполнением на стороне агента.
Но что указать в самой команде? Если указать просто путь к скрипту, то получаем ошибку "Unsupported item key".

**Comment by askkostya** [comment]
Здравствуйте. Скрипт ждет на входе IP адрес и порт на котором работает ККТ. Имеет смысл использовать только если подключено через сеть

**Comment by arzol72** [comment]
Понял, спасибо.
